{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.palexdev",
    "module": "materialfx",
    "version": "11.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.palexdev",
          "module": "virtualizedfx",
          "version": {
            "requires": "11.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "materialfx-11.16.0.jar",
          "url": "materialfx-11.16.0.jar",
          "size": 3229958,
          "sha512": "7ad39ec69737fa3244ebafe7fcb73ab401bbd7b043c38ac6b5bd63484d7bd2d8a745fd4465af335bb7e1bd07d16281ab53923de823b54f50adf55664e23e1a48",
          "sha256": "0cabfb97416b2febf26d621eccd1ff08ccf6643e7761939667f3638dd60e7cc5",
          "sha1": "f6af931fdda91eb9b405036d54dd3ec7e5c9da3e",
          "md5": "96694b95b15da282cb794306a3bba237"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.palexdev",
          "module": "virtualizedfx",
          "version": {
            "requires": "11.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "materialfx-11.16.0.jar",
          "url": "materialfx-11.16.0.jar",
          "size": 3229958,
          "sha512": "7ad39ec69737fa3244ebafe7fcb73ab401bbd7b043c38ac6b5bd63484d7bd2d8a745fd4465af335bb7e1bd07d16281ab53923de823b54f50adf55664e23e1a48",
          "sha256": "0cabfb97416b2febf26d621eccd1ff08ccf6643e7761939667f3638dd60e7cc5",
          "sha1": "f6af931fdda91eb9b405036d54dd3ec7e5c9da3e",
          "md5": "96694b95b15da282cb794306a3bba237"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "materialfx-11.16.0-all.jar",
          "url": "materialfx-11.16.0-all.jar",
          "size": 3549352,
          "sha512": "70fde90ee2dd6742cd9beb2cf7ff24b045dad769301384bc449ff4339f9ea5540b57e4ba7f48ae48ba492bf296e02c0625c376ba4240ebacd087e506b23c12c8",
          "sha256": "66721766b63d660a6b2d48e254e02e912a8fac11e98a5cf69a9016cb637f8229",
          "sha1": "8f5df1133e63dacce625c9d4da40f3efe9e5e4fa",
          "md5": "ed212822338bc329a01934e6fcbf2b37"
        }
      ]
    }
  ]
}
