{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.palexdev",
    "module": "mfxcore",
    "version": "11.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.palexdev",
          "module": "mfxlocalization",
          "version": {
            "requires": "11.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mfxcore-11.3.0.jar",
          "url": "mfxcore-11.3.0.jar",
          "size": 336922,
          "sha512": "8f8165b7f0e4446c4d48f09b69b4457d69ac25b673ea845c160fdd3430deb433e22e5abe4acc266bdd2674cd91f08e6682debc87c241aab363224b7af6f1a90b",
          "sha256": "a8fbe27dde3b8ffebb2b0c552f99a190a30ab2ab399cfcf731fe315a6979d373",
          "sha1": "4d91c09a41c3e58bbb63d2ba641cc0c41f2ee4bd",
          "md5": "88beb58450a5df6634c543a7c6009e79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.palexdev",
          "module": "mfxlocalization",
          "version": {
            "requires": "11.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mfxcore-11.3.0.jar",
          "url": "mfxcore-11.3.0.jar",
          "size": 336922,
          "sha512": "8f8165b7f0e4446c4d48f09b69b4457d69ac25b673ea845c160fdd3430deb433e22e5abe4acc266bdd2674cd91f08e6682debc87c241aab363224b7af6f1a90b",
          "sha256": "a8fbe27dde3b8ffebb2b0c552f99a190a30ab2ab399cfcf731fe315a6979d373",
          "sha1": "4d91c09a41c3e58bbb63d2ba641cc0c41f2ee4bd",
          "md5": "88beb58450a5df6634c543a7c6009e79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mfxcore-11.3.0-sources.jar",
          "url": "mfxcore-11.3.0-sources.jar",
          "size": 269201,
          "sha512": "ea609f983b01a71cf0011d4cc75fd3a7038a993c10691a197274cc084fa96a832b41329ae726d0c33a9a294212e598f3ca1a0bf34ab73d97fd2d9f7ef9a22615",
          "sha256": "b2dd9d706b95c5d7e11e84c29fd126f7fc1aa7b53847d25637e434b1f05462ce",
          "sha1": "d5f9479effea6da56380379f3cb8e591395d785a",
          "md5": "b40e8c68e4d27d786ecbd75e8531f644"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mfxcore-11.3.0-javadoc.jar",
          "url": "mfxcore-11.3.0-javadoc.jar",
          "size": 1009526,
          "sha512": "4f234b56a63e2029cac6c32523deee1d5892658430c87bbbc9186124b2aa4d5e9b158efe1c5170e9ed7bcc7956fbfe05cc2fdcf19c85037e61519b4c7edcfab8",
          "sha256": "9b8b732683d3c288d86cddcc00ef69f3d2e8e2b258c19cde88b62cd3b4ca883f",
          "sha1": "5e08a192ea26b93eb75fcb6fbf73846c20e2e85d",
          "md5": "3e7b150736a10167d0b79252a0769a96"
        }
      ]
    }
  ]
}
